name: Publish Python package to PyPI

on:
  push:
    branches:
      - release  # Trigger when pushing to the main branch. Adjust this to match your default branch.
  workflow_dispatch:  # Allow manual triggering of the workflow from GitHub UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust the Python version to match your package requirements.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Install build tools

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel  # Adjust if using a different build system like pyproject.toml

    - name: Publish to PyPI
      run: |
        twine upload dist/*  # Upload the generated distribution files to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # PyPI Username (stored in GitHub Secrets)
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # PyPI Password or token (stored in GitHub Secrets)
